config/routes.rb
Rails.application.routes.draw do
  root to: 'main#top'
  get 'main/about'
  devise_for :users
  resources :books
  resources :users, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
    validates :opinion, presence: true
    validates :opinion, length: { in: 1..200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :book,  dependent: :destroy
  attachment :user_image
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?


	def after_sign_in_path_for(resource)
	  user_path(current_user)
	end

	def after_sign_out_path_for(resource)
	  root_path
	end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def ensure_correct_user
    book = Book.find(params[:id])
    if current_user.id !=  book.user_id
     redirect_to books_path
    end
  end

 def new
  	@book = Book.new
  end
  def create
  	book = Book.new(book_params)
  	book.user_id = current_user.id
  	if book.save
      flash[:notice]= "Created succesfuly"
      redirect_to book_path(book.id)
    else
      @book = book
      @books = Book.all
      render :index
    end
  end
  def index
    @book = Book.new
  	@books = Book.all
  end

  def show
    @book = Book.new
    @book_detail = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]= "Updated succesfuly"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to user_path(current_user.id)
  end

  private
  def book_params
  	params.require(:book).permit(:title, :opinion)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  	@users = User.all
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
  	@books = @user.book.all
    @book = Book.new
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def edit
  	@user = User.find(current_user.id)
    @book = Book.new
  end
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Editing Book</h1>
		<%= form_for(@book) do |f| %>
		<% if @book.errors.any? %>
	       <%= pluralize(@book.errors.count,"error") %>prohibited this obj from being saved:
	      <ul>
	        <% @book.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	        <% end %>
	      </ul>
	    <% end %>
	<div class="field row">
		<label>Title</label>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>
	<div class="field row">
		<label>Opinion</label>
		<%= f.text_area :opinion, class: "col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= f.submit 'Update', class: "btn btn-primary col-xs-12" %>
	</div>
		<% end %>
			<%= link_to 'Show', book_path(@book.id), class: "book_#{@book.id}" %> |
			<%= link_to 'Back', books_path, class: "back" %>
</div>

app/views/books/index.html.erb
<%= render 'users/list', user: current_user, book: @book %>


<div class="col-xs-9">
	<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<tbody>
				<thred>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
					<% @books.each do |book|%>
					<tr>
						<th><%= attachment_image_tag book.user, :user_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></th>
						<th><%= link_to book.title, book_path(book.id) %></th>
						<th><%= book.opinion%></th>
					</tr>
					<% end %>
				</thred>
			</tbody>
		</table>
</div>

app/views/books/show.html.erb
<%= render 'users/list', user: current_user, book: @book  %>

<div class="col-xs-9">
	<h2>Book detail</h2>
		<table class="table table-hover table-inverse">
			<tbody>
				<thred>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
						<th></th>
					</tr>
					<tr>
						<th><%= attachment_image_tag @book_detail.user, :user_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></th>
						<th><%= @book_detail.title%></th>
						<th><%= @book_detail.opinion%></th>
						<% if @book_detail.user_id == current_user.id %>
						<th><%= link_to 'Edit', edit_book_path(@book_detail), class: "btn-sm btn-success edit_book_#{@book_detail.id}" %></th>
						<th><%= link_to 'Destroy', book_path(@book_detail.id), method: :delete, class: "btn-sm btn-danger destroy_book#{@book_detail.id}", data: { confirm: '本当に消しますか？' } %></th>
						<% end %>
					</tr>
				</thred>
			</tbody>
		</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="navbar navbar-inverse">
    <div class="container">
    <nav class="nav navbar-nav navbar-left">
      <span>Bookers</span>
    </nav>
      <nav class="nav-list">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
            <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
            <li><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
            <li><%= link_to " About", main_about_path, class: "glyphicon glyphicon-link about" %></li>
            <li><%= link_to " signup", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
            <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          </ul>
        <% end %>
      </nav>
    </div>
  </header>

  <body>
    <% if flash[:notice] %>
      <p><%= flash[:notice]%></p>
    <% end %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/main/about.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>

app/views/main/top.html.erb
<div class="top-message col-md-offset-3 col-md-6">
<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
    <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about varioius books!</p>
<div class="btn-wrapper">
    <div class="row">
    	<p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
    </div>
    <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
    </div>
</div>

app/views/users/_list.html.erb
<% if book.errors.any? %>
       <%= pluralize(book.errors.count,"error") %>prohibited this obj from being saved:
      <ul>
        <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
<div class="col-xs-3">
	<h2>User Info</h2>
		<h3>Image</h3>
		<%= attachment_image_tag user, :user_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
		<table class="table">
			<tbody><tr></tr>
		      <tr>
		    	  <th>name</th>
		    	  <th><%= user.name %></th>
		      </tr>
		      <tr>
		    	  <th>introduction</th>
		    	  <th><%= user.introduction %></th>
		      </tr>
		   </tbody>
		</table>
		<div class="row">
			<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
		</div>

	<h2>New Book</h2>
	<%= form_for(book) do |t|%>
	<div class="field row">
		<label>Title</label>
		<%= t.text_field :title, class: "col-xs-12 book_title" %>
	</div>
	<div class="field row">
		<label>Opinion</label>
		<%= t.text_area :opinion, class: "col-xs-12 book_body" %>
	</div>
	<div class="actions row">
		<%= t.submit 'Create Book', class: "btn btn-primary col-xs-12"%>
	</div>
	<% end %>
</div>

app/views/users/_other_list.html.erb
<div class="col-xs-3">
	<h2>User Info</h2>
		<h3>Image</h3>
		<%= attachment_image_tag user, :user_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
		<table class="table">
			<tbody><tr></tr>
		      <tr>
		    	  <th>name</th>
		    	  <th><%= user.name %></th>
		      </tr>
		      <tr>
		    	  <th>introduction</th>
		    	  <th><%= user.introduction %></th>
		      </tr>
		   </tbody>
		</table>
</div>

app/views/users/edit.html.erb
<h1>User Info</h1>
<%= form_for(@user) do |f|%>
<div class="field row">
	<label>Name</label>
	<%= f.text_field :name, class: "name" %>
</div>
<div class="field row">
	<label>Image</label>
	<%= f.attachment_field :user_image, class: "user_image" %>
<div class="field row">
	<label>Introduction</label>
	<%= f.text_area :introduction, class: "introduction" %>
</div>
<div class="actions row">
	<%= f.submit 'Update User' %>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'users/list', user: current_user, book: @book  %>

<div class="col-xs-9">
	<h2>Users</h2>
		<table class="table table-hover table-inverse">
			<tbody>
				<thred>
					<tr>
						<th></th>
						<th>Image</th>
						<th>Name</th>
					</tr>
					<% @users.each do |user|%>
					<tr>
						<th><%= attachment_image_tag user, :user_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></th>
						<th><%= user.name%></th>
						<th><%= link_to 'Show', user_path(user.id), class: "book_#{user.id}" %></th>
					</tr>
					<% end %>
				</thred>
			</tbody>
		</table>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
<%= render 'users/list', user: current_user, book: @book %>
<% else %>
<%= render 'users/other_list', user: @user %>
<% end %>

<div class="col-xs-9">
	<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<tbody>
				<thred>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
					</tr>
					<% @books.each do |book|%>
					<tr>
						<th><%= attachment_image_tag book.user, :user_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></th>
						<th><%= link_to book.title, book_path(book.id) %></th>
						<th><%= book.opinion %></th>
					</tr>
				</thred>
			</tbody>
			<% end %>
		</table>
</div>